function Jac1 = autoGen_jacobianRight3(tx,T)
%AUTOGEN_JACOBIANRIGHT3
%    JAC1 = AUTOGEN_JACOBIANRIGHT3(TX,T)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    28-Jun-2023 20:11:59

t2 = T.^2;
t3 = tx.^2;
t4 = tx.^3;
Jac1 = [1.0./T.^5.*t4.*(t2.*1.0e+1+t3.*6.0-T.*tx.*1.5e+1),-1.0./t2.^2.*t4.*(t2.*4.0+t3.*3.0-T.*tx.*7.0),(1.0./T.^3.*t4.*(T-tx).^2)./2.0];
