function Jac3 = autoGen_jacobianLeft3(tx,T)
%AUTOGEN_JACOBIANLEFT3
%    JAC3 = AUTOGEN_JACOBIANLEFT3(TX,T)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    28-Jun-2023 20:12:00

t2 = tx.^2;
t3 = -tx;
t4 = T+t3;
t5 = t4.^3;
Jac3 = [1.0./T.^5.*t5.*(t2.*6.0+T.*tx.*3.0+T.^2),1.0./T.^4.*t5.*tx.*(T+tx.*3.0),(1.0./T.^3.*t2.*t5)./2.0];
